name: Test

on:
  push:
    branches-ignore: [main, release/**]

jobs:
  run-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - run: bash .ci/runChecks.sh

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v6
        with:
          node-version: current
      - uses: browser-actions/setup-chrome@v2
      - run: npm ci
      - run: npm run build
      - run: bash .ci/test.sh
    needs: ["run-checks"]
