name: Test

on:
  push:
    branches-ignore: [main, release/**]

jobs:
  run-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: bash .ci/runChecks.sh
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - uses: browser-actions/setup-chrome@v1
      - run: npm ci
      - run: npm run build
      - run: bash .ci/test.sh
    needs: ["run-checks"]
